name: 'PWJLM'
version: '${project.version}'
main: 'io.github.maximmaxims.pwjlm.PWJLM'
folia-supported: true
api-version: 1.19
softdepend: [ PlaceholderAPI, AuthMe ]
author: MaximMaximS
description: '${project.description}'
website: '${project.url}'
commands:
  pwjlm:
    description: Main command
    usage: /<command> [reload|help]
permissions:
  pwjlm.update:
    description: Receive update notification
    default: op
  pwjlm.command:
    description: Default command usage permission
    default: op
  pwjlm.command.reload:
    description: Allows config reload
    default: op
